name: Docker Remote Deploy
author: rynocouse
description: Run docker container on remote server via ssh.
inputs:
    remote_docker_host:
        description: The address of the remote docker host.
    ssh_private_key:
        description: Private SSH Key to access Docker host.
    stack_file_name:
        description: Docker compose file name default docker-compose.yml.
        required: false
    region:
        description: AWS Region to use.  Defaults to us-east-1.
        required: false
    direction:
        description: Whether to "push" or "pull" the image.  Defaults to "push".
        required: false
runs:
    using: node12
    main: 'main.js'
branding:
    icon: upload
    color: orange
